VisionServer: lib-vs/additions/cpp-tools/src/basic.cpp File Reference
basic.cpp File Reference
#include "basic.h"
Functions
uint8_t toNumSafe (char num)
char clearEnd (std::string &str)
void replace (std::string &str, const std::string find, const char *replace)
const char * dateStamp ()
const char * dateStamp (time_t *tme)
const char * safeNull (const char *str)
size_t safeLen (const char *str)
std::string withTime (const char *message)
void exitError (const char *message)
Function Documentation
toNumSafe()
uint8_t toNumSafe (char num)
Definition at line 3 of file basic.cpp.
clearEnd()
char clearEnd (std::string & str)
Definition at line 10 of file basic.cpp.
Referenced by Response::Response(), HeaderList::add(), and Request::parse().
replace()
void replace (std::string & str, const std::string find, const char * replace)
Definition at line 21 of file basic.cpp.
References replace().
Referenced by replace(), and HttpServer::HttpHandler::respond().
dateStamp() [1/2]
const char * dateStamp ()
Definition at line 25 of file basic.cpp.
Referenced by debug(), HttpServer::ex_lerror(), HttpServer::lerror(), HttpServer::HttpFormatter::onConnect(), HttpServer::HttpFormatter::onDisconnect(), HttpServer::HttpFormatter::onRequest(), HttpServer::HttpFormatter::onResponse(), HttpServer::HttpFormatter::onServerStart(), SigHandle::printExit(), SigHandle::printIgnore(), and withTime().
dateStamp() [2/2]
const char * dateStamp (time_t * tme)
Definition at line 39 of file basic.cpp.
safeNull()
const char * safeNull (const char * str)
Definition at line 52 of file basic.cpp.
safeLen()
size_t safeLen (const char * str)
Definition at line 55 of file basic.cpp.
withTime()
std::string withTime (const char * message)
Definition at line 59 of file basic.cpp.
References dateStamp().
Referenced by HttpServer::estop(), exitError(), and HttpServer::HttpFormatter::onServerEnd().
exitError()
void exitError (const char * message)
Definition at line 67 of file basic.cpp.
References withTime().