VisionServer: Response Class Reference
Response Class Reference
#include <http.h>
Public Member Functions
Response ()=delete
Response (Version version=Version::HTTP_1_1)
Response (Code responsecode, const HeaderList &headers, const std::string &body=std::string(), Version version=Version::HTTP_1_1)
Response (const std::string &response)
Response (const Response &other)
Response (Response &&other)
~Response ()=default
void update (Code responsecode, const std::vector< Segment > &headers, const std::string &body=std::string())
void update (Code responsecode, HeaderList &headers, const std::string &body=std::string())
std::string getSerialized () const
Code * intCode ()
Version * intVersion ()
std::string * intBody ()
HeaderList * intHeaders ()
const Code getCode () const
const Version getVersion () const
const std::string & getBody () const
const HeaderList & getHeaders () const
size_t bodyLen () const
Static Public Member Functions
static std::string getSerialized (Code responsecode, std::vector< Segment > &headers, const std::string &body=std::string(), Version version=Version::HTTP_1_1)
static void getSerialized (std::ostream &buffer, Code responsecode, std::vector< Segment > &headers, const std::string &body=std::string(), Version version=Version::HTTP_1_1)
Private Attributes
Code responsecode
Version version
HeaderList headers
std::string body
Detailed Description
Definition at line 191 of file http.h.
Constructor & Destructor Documentation
Response() [1/6]
Response::Response () delete
Response() [2/6]
Response::Response (Version version = Version::HTTP_1_1) inline
Definition at line 200 of file http.h.
Response() [3/6]
Response::Response (Code responsecode, const HeaderList & headers, const std::string & body = std::string(), Version version = Version::HTTP_1_1) inline
Definition at line 201 of file http.h.
Response() [4/6]
Response::Response (const std::string & response)
Definition at line 319 of file http.cpp.
References HeaderList::add(), body, clearEnd(), Versions::getType(), Codes::getType(), headers, responsecode, space, and version.
Response() [5/6]
Response::Response (const Response & other) inline
Definition at line 204 of file http.h.
Response() [6/6]
Response::Response (Response && other) inline
Definition at line 205 of file http.h.
~Response()
Response::~Response () default
Member Function Documentation
update() [1/2]
void Response::update (Code responsecode, const std::vector< Segment > & headers, const std::string & body = std::string())
Definition at line 337 of file http.cpp.
References body, headers, and responsecode.
update() [2/2]
void Response::update (Code responsecode, HeaderList & headers, const std::string & body = std::string())
Definition at line 342 of file http.cpp.
References HeaderList::add(), body, headers, HeaderList::intHeaders(), and responsecode.
getSerialized() [1/3]
std::string Response::getSerialized () const
Definition at line 348 of file http.cpp.
References HeaderList::allHeaders(), body, endline, Codes::getString(), Versions::getString(), headers, responsecode, space, and version.
intCode()
Code * Response::intCode () inline
Definition at line 212 of file http.h.
References responsecode.
intVersion()
Version * Response::intVersion () inline
Definition at line 213 of file http.h.
References version.
intBody()
std::string * Response::intBody () inline
Definition at line 214 of file http.h.
References body.
intHeaders()
HeaderList * Response::intHeaders () inline
Definition at line 215 of file http.h.
References headers.
getCode()
const Code Response::getCode () const inline
Definition at line 217 of file http.h.
References responsecode.
getVersion()
const Version Response::getVersion () const inline
Definition at line 218 of file http.h.
References version.
getBody()
const std::string & Response::getBody () const inline
Definition at line 219 of file http.h.
References body.
getHeaders()
const HeaderList & Response::getHeaders () const inline
Definition at line 220 of file http.h.
References headers.
bodyLen()
size_t Response::bodyLen () const inline
Definition at line 222 of file http.h.
getSerialized() [2/3]
std::string Response::getSerialized (Code responsecode, std::vector< Segment > & headers, const std::string & body = std::string(), Version version = Version::HTTP_1_1) static
Definition at line 359 of file http.cpp.
References body, endline, Codes::getString(), Versions::getString(), headers, responsecode, space, and version.
getSerialized() [3/3]
void Response::getSerialized (std::ostream & buffer, Code responsecode, std::vector< Segment > & headers, const std::string & body = std::string(), Version version = Version::HTTP_1_1) static
Definition at line 370 of file http.cpp.
References body, endline, Codes::getString(), Versions::getString(), headers, responsecode, space, and version.
Member Data Documentation
responsecode
Code Response::responsecode private
Definition at line 193 of file http.h.
Referenced by Response(), getCode(), getSerialized(), intCode(), and update().
version
Version Response::version private
Definition at line 194 of file http.h.
Referenced by Response(), getSerialized(), getVersion(), and intVersion().
headers
HeaderList Response::headers private
Definition at line 195 of file http.h.
Referenced by Response(), getHeaders(), getSerialized(), intHeaders(), and update().
body
std::string Response::body private
Definition at line 196 of file http.h.
Referenced by Response(), getBody(), getSerialized(), intBody(), and update().
The documentation for this class was generated from the following files:
lib-vs/additions/cpp-tools/src/server/http.h
lib-vs/additions/cpp-tools/src/server/http.cpp