VisionServer: olstream Class Reference
olstream Class Reference
#include <output.h>
Public Member Functions
olstream ()
olstream (const char *file, const OMODE modes=std::ios::out)
olstream (const OMODE modes)
olstream (std::ostream *stream)
olstream (std::ostream *stream, const char *file, const OMODE modes=std::ios::out)
olstream (const olstream &other)
olstream (olstream &&other)
~olstream ()
void operator= (const olstream &other)
void operator= (olstream &&other)
void setModes (const OMODE modes)
void addModes (const OMODE modes)
void setStream (const char *file)
void setStream (const char *file, const OMODE modes)
void setStream (std::ostream *stream=&std::cout)
std::ostream & getStream ()
const char * getPath ()
std::ostream & open ()
void close ()
template<typename t >
olstream & operator<< (t item)
template<typename t >
olstream & operator<<= (t item)
template<typename t >
olstream & operator<= (t item)
template<typename t >
olstream & operator< (t item)
Protected Member Functions
bool checkStream ()
std::ostream & streamGuard ()
Private Attributes
bool fmode
std::ofstream file
std::ostream * stream
char * fname
OMODE omodes
Detailed Description
Definition at line 13 of file output.h.
Constructor & Destructor Documentation
olstream() [1/7]
olstream::olstream ()
Definition at line 4 of file output.cpp.
olstream() [2/7]
olstream::olstream (const char * file, const OMODE modes = std::ios::out)
Definition at line 6 of file output.cpp.
References file, and fname.
olstream() [3/7]
olstream::olstream (const OMODE modes)
Definition at line 12 of file output.cpp.
olstream() [4/7]
olstream::olstream (std::ostream * stream)
Definition at line 14 of file output.cpp.
olstream() [5/7]
olstream::olstream (std::ostream * stream, const char * file, const OMODE modes = std::ios::out)
Definition at line 16 of file output.cpp.
References file, and fname.
olstream() [6/7]
olstream::olstream (const olstream & other)
Definition at line 22 of file output.cpp.
References fname.
olstream() [7/7]
olstream::olstream (olstream && other)
Definition at line 33 of file output.cpp.
References checkStream().
~olstream()
olstream::~olstream ()
Definition at line 41 of file output.cpp.
References fname.
Member Function Documentation
checkStream()
bool olstream::checkStream () inline protected
Definition at line 77 of file output.cpp.
References stream.
Referenced by olstream(), and operator=().
streamGuard()
std::ostream & olstream::streamGuard () protected
Definition at line 84 of file output.cpp.
References stream.
Referenced by getStream(), open(), operator<(), operator<<(), operator<<=(), and operator<=().
operator=() [1/2]
void olstream::operator= (const olstream & other)
Definition at line 45 of file output.cpp.
References checkStream(), fmode, fname, omodes, and stream.
operator=() [2/2]
void olstream::operator= (olstream && other)
Definition at line 61 of file output.cpp.
References checkStream(), file, fmode, fname, omodes, and stream.
setModes()
void olstream::setModes (const OMODE modes)
Definition at line 91 of file output.cpp.
References omodes.
Referenced by HttpServer::HttpServer(), HttpServer::setLog(), and SigHandle::setLog().
addModes()
void olstream::addModes (const OMODE modes)
Definition at line 94 of file output.cpp.
References omodes.
setStream() [1/3]
void olstream::setStream (const char * file)
Definition at line 97 of file output.cpp.
References file, fmode, and fname.
Referenced by HttpServer::setLog(), and SigHandle::setLog().
setStream() [2/3]
void olstream::setStream (const char * file, const OMODE modes)
Definition at line 106 of file output.cpp.
References file, fmode, fname, and omodes.
setStream() [3/3]
void olstream::setStream (std::ostream * stream = &std::cout)
Definition at line 115 of file output.cpp.
References fmode, and stream.
getStream()
std::ostream & olstream::getStream ()
Definition at line 120 of file output.cpp.
References streamGuard().
Referenced by HttpServer::defLog().
getPath()
const char * olstream::getPath ()
Definition at line 123 of file output.cpp.
References fname.
open()
std::ostream & olstream::open ()
Definition at line 127 of file output.cpp.
References file, fname, and streamGuard().
Referenced by operator<<(), and operator<<=().
close()
void olstream::close ()
Definition at line 136 of file output.cpp.
References file.
Referenced by operator<().
operator<<()
template<typename t > olstream & olstream::operator<< (t item) inline
Definition at line 51 of file output.h.
References open(), and streamGuard().
operator<<=()
template<typename t > olstream & olstream::operator<<= (t item) inline
Definition at line 65 of file output.h.
References open(), and streamGuard().
operator<=()
template<typename t > olstream & olstream::operator<= (t item) inline
Definition at line 76 of file output.h.
References streamGuard().
operator<()
template<typename t > olstream & olstream::operator< (t item) inline
Definition at line 86 of file output.h.
References close(), and streamGuard().
Member Data Documentation
fmode
bool olstream::fmode private
Definition at line 15 of file output.h.
Referenced by operator=(), and setStream().
file
std::ofstream olstream::file private
Definition at line 16 of file output.h.
Referenced by olstream(), close(), open(), operator=(), and setStream().
stream
std::ostream* olstream::stream private
Definition at line 17 of file output.h.
Referenced by checkStream(), operator=(), setStream(), and streamGuard().
fname
char* olstream::fname private
Definition at line 18 of file output.h.
Referenced by olstream(), ~olstream(), getPath(), open(), operator=(), and setStream().
omodes
OMODE olstream::omodes private
Definition at line 19 of file output.h.
Referenced by addModes(), operator=(), setModes(), and setStream().
The documentation for this class was generated from the following files:
lib-vs/additions/cpp-tools/src/output.h
lib-vs/additions/cpp-tools/src/output.cpp