VisionServer: HeaderList Class Reference
HeaderList Class Reference
#include <http.h>
Public Member Functions
HeaderList ()=default
HeaderList (const std::vector< Segment > &list)
HeaderList (std::vector< Segment > &&list)
HeaderList (const size_t size)
HeaderList (const HeaderList &other)
HeaderList (HeaderList &&other)
HeaderList (const std::string &body)
~HeaderList ()=default
void add (const Segment &header)
void add (const std::string &key, const std::string &value)
void add (const std::vector< Segment > &list)
void add (const std::string &body)
void reserve (size_t reserve)
void reset ()
std::string find (std::string key) const
std::string allHeaders () const
std::vector< Segment > * intHeaders ()
const std::vector< Segment > & getHeaders () const
Static Public Member Functions
static std::unordered_map< std::string, std::string > headerMap (const std::vector< Segment > &headers)
Private Attributes
std::vector< Segment > headers
Detailed Description
Definition at line 115 of file http.h.
Constructor & Destructor Documentation
HeaderList() [1/7]
HeaderList::HeaderList () default
HeaderList() [2/7]
HeaderList::HeaderList (const std::vector< Segment > & list) inline
Definition at line 121 of file http.h.
HeaderList() [3/7]
HeaderList::HeaderList (std::vector< Segment > && list) inline
Definition at line 122 of file http.h.
HeaderList() [4/7]
HeaderList::HeaderList (const size_t size)
Definition at line 188 of file http.cpp.
References headers.
HeaderList() [5/7]
HeaderList::HeaderList (const HeaderList & other) inline
Definition at line 124 of file http.h.
HeaderList() [6/7]
HeaderList::HeaderList (HeaderList && other) inline
Definition at line 125 of file http.h.
HeaderList() [7/7]
HeaderList::HeaderList (const std::string & body)
Definition at line 191 of file http.cpp.
References add().
~HeaderList()
HeaderList::~HeaderList () default
Member Function Documentation
add() [1/4]
void HeaderList::add (const Segment & header)
Definition at line 195 of file http.cpp.
References headers.
Referenced by HeaderList(), Response::Response(), Request::parse(), HttpServer::HttpHandler::respond(), and Response::update().
add() [2/4]
void HeaderList::add (const std::string & key, const std::string & value)
Definition at line 198 of file http.cpp.
References headers.
add() [3/4]
void HeaderList::add (const std::vector< Segment > & list)
Definition at line 201 of file http.cpp.
References headers.
add() [4/4]
void HeaderList::add (const std::string & body)
Definition at line 205 of file http.cpp.
References clearEnd(), and headers.
reserve()
void HeaderList::reserve (size_t reserve)
Definition at line 215 of file http.cpp.
References headers.
reset()
void HeaderList::reset ()
Definition at line 218 of file http.cpp.
References headers.
Referenced by Request::parse().
find()
std::string HeaderList::find (std::string key) const
Definition at line 223 of file http.cpp.
References headerMap(), and headers.
allHeaders()
std::string HeaderList::allHeaders () const
Definition at line 231 of file http.cpp.
References endline, and headers.
Referenced by Request::getSerialized(), and Response::getSerialized().
intHeaders()
std::vector< Segment > * HeaderList::intHeaders ()
Definition at line 239 of file http.cpp.
References headers.
Referenced by Response::update().
getHeaders()
const std::vector< Segment > & HeaderList::getHeaders () const
Definition at line 242 of file http.cpp.
References headers.
headerMap()
std::unordered_map< std::string, std::string > HeaderList::headerMap (const std::vector< Segment > & headers) static
Definition at line 246 of file http.cpp.
References headers.
Referenced by find().
Member Data Documentation
headers
std::vector<Segment> HeaderList::headers private
Definition at line 117 of file http.h.
Referenced by HeaderList(), add(), allHeaders(), find(), getHeaders(), headerMap(), intHeaders(), reserve(), and reset().
The documentation for this class was generated from the following files:
lib-vs/additions/cpp-tools/src/server/http.h
lib-vs/additions/cpp-tools/src/server/http.cpp