VisionServer: HttpServer::HttpFormatter Class Reference
HttpServer::HttpFormatter Class Reference
#include <server.h>
Public Member Functions
HttpFormatter (HttpServer &server)
virtual void onServerStart ()
virtual void onConnect (int fd, const char *ip)
virtual void onRequest (int fd, const char *ip, int readlen, const Request *req=nullptr, const char *resource=nullptr)
virtual void onResponse (int fd, const char *ip, int sent, const Response *resp=nullptr, const char *resource=nullptr)
virtual void onDisconnect (int fd, const char *ip)
virtual void onServerEnd ()
Protected Member Functions
olstream * getStream ()
Version * getVer ()
HttpFormatter ()
HttpFormatter (HttpServer *outer)
virtual void update (HttpServer *outer)
Protected Attributes
HttpServer * that
Friends
class HttpServer
Detailed Description
Definition at line 47 of file server.h.
Constructor & Destructor Documentation
HttpFormatter() [1/3]
HttpServer::HttpFormatter::HttpFormatter () inline protected
Definition at line 54 of file server.h.
HttpFormatter() [2/3]
HttpServer::HttpFormatter::HttpFormatter (HttpServer * outer) inline protected
Definition at line 55 of file server.h.
HttpFormatter() [3/3]
HttpServer::HttpFormatter::HttpFormatter (HttpServer & server) inline
Definition at line 59 of file server.h.
Member Function Documentation
getStream()
olstream * HttpServer::HttpFormatter::getStream () protected
Definition at line 40 of file server.cpp.
References HttpServer::logs, and that.
getVer()
Version * HttpServer::HttpFormatter::getVer () protected
Definition at line 43 of file server.cpp.
update()
void HttpServer::HttpFormatter::update (HttpServer * outer) protected virtual
Definition at line 47 of file server.cpp.
onServerStart()
void HttpServer::HttpFormatter::onServerStart () virtual
Definition at line 51 of file server.cpp.
References dateStamp(), and Versions::getString().
onConnect()
void HttpServer::HttpFormatter::onConnect (int fd, const char * ip) virtual
Definition at line 54 of file server.cpp.
References dateStamp(), and BaseServer::ip.
onRequest()
void HttpServer::HttpFormatter::onRequest (int fd, const char * ip, int readlen, const Request * req = nullptr, const char * resource = nullptr) virtual
Definition at line 57 of file server.cpp.
References dateStamp(), BaseServer::ip, and newline.
Referenced by HttpServer::HttpHandler::respond().
onResponse()
void HttpServer::HttpFormatter::onResponse (int fd, const char * ip, int sent, const Response * resp = nullptr, const char * resource = nullptr) virtual
Definition at line 60 of file server.cpp.
References dateStamp(), BaseServer::ip, and newline.
Referenced by HttpServer::HttpHandler::respond().
onDisconnect()
void HttpServer::HttpFormatter::onDisconnect (int fd, const char * ip) virtual
Definition at line 63 of file server.cpp.
References dateStamp(), and BaseServer::ip.
onServerEnd()
void HttpServer::HttpFormatter::onServerEnd () virtual
Definition at line 66 of file server.cpp.
References withTime().
Friends And Related Function Documentation
HttpServer
friend class HttpServer friend
Definition at line 48 of file server.h.
Member Data Documentation
that
HttpServer* HttpServer::HttpFormatter::that protected
Definition at line 50 of file server.h.
Referenced by getStream().
The documentation for this class was generated from the following files:
lib-vs/additions/cpp-tools/src/server/server.h
lib-vs/additions/cpp-tools/src/server/server.cpp