VisionServer: SigHandle Class Reference
SigHandle Class Reference
#include <sighandle.h>
Public Types
enum class Sigs {
ERR , HUP , INT , QUIT ,
ILL , TRAP , ABRT , BUS ,
FPE , KILL , USR1 , SEGV ,
USR2 , PIPE , ALRM , TERM ,
STKFLT , CHLD , CONT , STOP ,
STP , TTIN , TTOU , URG ,
XCPU , XFSZ , VTALRM , PROF ,
WINCH , IOA , PWR , SYSC
}
typedef void(* __sighandler_t) (int)
Public Member Functions
void setLog (const std::ios::openmode modes)
void setLog (const char *file)
void setLog (const char *file, const std::ios::openmode modes)
void setLog (std::ostream *stream)
void setLog (olstream &&target)
void setLog (const olstream &target)
void reset (std::initializer_list< Sigs > exit=def_ex, std::initializer_list< Sigs > ingore=def_ign)
void setup (__sighandler_t exit, __sighandler_t ignore=printIgnore)
void setup (__sighandler_t exit, std::initializer_list< Sigs > exl, std::initializer_list< Sigs > ignl, __sighandler_t ignore=printIgnore)
Static Public Member Functions
static SigHandle & get ()
static void printIgnore (int signum)
static void printExit (int signum)
static void sigIgnore (int signum)
static void sigExit (int signum)
Private Member Functions
SigHandle ()
SigHandle (const SigHandle &)=delete
void sigSet (__sighandler_t exit, __sighandler_t ignore=printIgnore)
void sigSet ()
Private Attributes
std::vector< Sigs > ign_sigs
std::vector< Sigs > exit_sigs
Static Private Attributes
static const std::array< const char *, 31 > sigmap
static const std::initializer_list< Sigs > def_ign
static const std::initializer_list< Sigs > def_ex
Detailed Description
Definition at line 12 of file sighandle.h.
Member Typedef Documentation
__sighandler_t
typedef void(* SigHandle::__sighandler_t) (int)
Definition at line 17 of file sighandle.h.
Member Enumeration Documentation
Sigs
enum class SigHandle::Sigs strong
Enumerator
ERR
HUP
INT
QUIT
ILL
TRAP
ABRT
BUS
FPE
KILL
USR1
SEGV
USR2
PIPE
ALRM
TERM
STKFLT
CHLD
CONT
STOP
STP
TTIN
TTOU
URG
XCPU
XFSZ
VTALRM
PROF
WINCH
IOA
PWR
SYSC
Definition at line 19 of file sighandle.h.
Constructor & Destructor Documentation
SigHandle() [1/2]
SigHandle::SigHandle () private
Definition at line 29 of file sighandle.cpp.
References setLog(), and sigSet().
SigHandle() [2/2]
SigHandle::SigHandle (const SigHandle &) private delete
Member Function Documentation
get()
SigHandle & SigHandle::get () static
Definition at line 107 of file sighandle.cpp.
printIgnore()
void SigHandle::printIgnore (int signum) static
Definition at line 112 of file sighandle.cpp.
References dateStamp(), sigmap, and sigout.
Referenced by sigIgnore().
printExit()
void SigHandle::printExit (int signum) static
Definition at line 115 of file sighandle.cpp.
References dateStamp(), sigmap, and sigout.
Referenced by sigExit().
sigIgnore()
void SigHandle::sigIgnore (int signum) static
Definition at line 118 of file sighandle.cpp.
References printIgnore().
Referenced by sigSet().
sigExit()
void SigHandle::sigExit (int signum) static
Definition at line 121 of file sighandle.cpp.
References printExit().
Referenced by sigSet().
setLog() [1/6]
void SigHandle::setLog (const std::ios::openmode modes)
Definition at line 164 of file sighandle.cpp.
References olstream::setModes(), and sigout.
Referenced by SigHandle().
setLog() [2/6]
void SigHandle::setLog (const char * file)
Definition at line 167 of file sighandle.cpp.
References olstream::setStream(), and sigout.
setLog() [3/6]
void SigHandle::setLog (const char * file, const std::ios::openmode modes)
Definition at line 170 of file sighandle.cpp.
References olstream::setStream(), and sigout.
setLog() [4/6]
void SigHandle::setLog (std::ostream * stream)
Definition at line 173 of file sighandle.cpp.
References olstream::setStream(), and sigout.
setLog() [5/6]
void SigHandle::setLog (olstream && target)
Definition at line 176 of file sighandle.cpp.
References sigout.
setLog() [6/6]
void SigHandle::setLog (const olstream & target)
Definition at line 179 of file sighandle.cpp.
References sigout.
reset()
void SigHandle::reset (std::initializer_list< Sigs > exit = def_ex, std::initializer_list< Sigs > ingore = def_ign)
Definition at line 182 of file sighandle.cpp.
References exit_sigs, ign_sigs, and sigSet().
setup() [1/2]
void SigHandle::setup (__sighandler_t exit, __sighandler_t ignore = printIgnore)
Definition at line 187 of file sighandle.cpp.
References sigSet().
setup() [2/2]
void SigHandle::setup (__sighandler_t exit, std::initializer_list< Sigs > exl, std::initializer_list< Sigs > ignl, __sighandler_t ignore = printIgnore)
Definition at line 190 of file sighandle.cpp.
References exit_sigs, ign_sigs, and sigSet().
sigSet() [1/2]
void SigHandle::sigSet (__sighandler_t exit, __sighandler_t ignore = printIgnore) private
Definition at line 37 of file sighandle.cpp.
References exit_sigs, and ign_sigs.
sigSet() [2/2]
void SigHandle::sigSet () private
Definition at line 97 of file sighandle.cpp.
References exit_sigs, ign_sigs, sigExit(), and sigIgnore().
Referenced by SigHandle(), reset(), and setup().
Member Data Documentation
sigmap
const std::array< const char *, 31 > SigHandle::sigmap static private
Initial value:
= {
    "console hangup", "keyboard interrupt", "quit request",
    "illegal CPU instruction", "trace request", "abort",
    "invalid bus address", "floating point arithmetic error, likely div/0",
    "program killed (unblockable)", "custom signal, not from os",
    "segmentation violation - check for bad '*/&'", "custom signal, not from os",
    "broken pipe", "alarm", "request to terminate", "stack fault",
    "child status has changed", "command to continue",
    "program stopped (unblockable)", "keyboard stop", "backround terminal read",
    "backround terminal write", "urgent socket condition", "CPU limit exceeded",
    "file size limit exceeded", "virtual alarm", "profiling alarm",
    "window size change", "IO now possible", "power restart (terminate)", "bad system call",
}
Definition at line 54 of file sighandle.h.
Referenced by printExit(), and printIgnore().
def_ign
const std::initializer_list< SigHandle::Sigs > SigHandle::def_ign static private
Initial value:
= {
    Sigs::HUP, Sigs::TRAP, Sigs::USR1, Sigs::USR2, Sigs::PIPE, Sigs::ALRM,
    Sigs::CHLD, Sigs::CONT, Sigs::STP, Sigs::TTIN, Sigs::TTOU, Sigs::URG,
    Sigs::VTALRM, Sigs::PROF, Sigs::WINCH, Sigs::IOA, Sigs::SYSC
}
Definition at line 55 of file sighandle.h.
def_ex
const std::initializer_list< SigHandle::Sigs > SigHandle::def_ex static private
Initial value:
= {
    Sigs::INT, Sigs::QUIT, Sigs::ILL, Sigs::ABRT, Sigs::BUS, Sigs::FPE,
    Sigs::SEGV, Sigs::TERM, Sigs::STKFLT, Sigs::XCPU, Sigs::XFSZ, Sigs::PWR
}
Definition at line 55 of file sighandle.h.
ign_sigs
std::vector<Sigs> SigHandle::ign_sigs private
Definition at line 57 of file sighandle.h.
Referenced by reset(), setup(), and sigSet().
exit_sigs
std::vector<Sigs> SigHandle::exit_sigs private
Definition at line 57 of file sighandle.h.
Referenced by reset(), setup(), and sigSet().
The documentation for this class was generated from the following files:
lib-vs/additions/cpp-tools/src/sighandle.h
lib-vs/additions/cpp-tools/src/sighandle.cpp