VisionServer: StopWatch Class Reference
StopWatch Class Reference
#include <timing.h>
Public Member Functions
StopWatch (olstream &&out=&std::cout, uint8_t settings=(ON_EXIT|NOW))
StopWatch (const char *scope, const olstream &out=&std::cout, uint8_t settings=(ON_EXIT|NOW))
StopWatch (const char *scope, olstream &&out=&std::cout, uint8_t settings=(ON_EXIT|NOW))
StopWatch (const char *scope, olstream *out, uint8_t settings=(ON_EXIT|NOW))
~StopWatch ()
void setStart ()
double getDuration ()
void print ()
void print (olstream &&out)
void end ()
void end (olstream &&out)
Static Public Attributes
static constexpr uint8_t ON_EXIT = 2
static constexpr uint8_t NOW = 1
Private Attributes
CHRONO::time_point< CHRONO::high_resolution_clock > ref
uint8_t settings
olstream buff
olstream * output
const char * scope
Detailed Description
Definition at line 19 of file timing.h.
Constructor & Destructor Documentation
StopWatch() [1/4]
StopWatch::StopWatch (olstream && out = &std::cout, uint8_t settings = (ON_EXIT | NOW))
Definition at line 15 of file timing.cpp.
References NOW, setStart(), and settings.
StopWatch() [2/4]
StopWatch::StopWatch (const char * scope, const olstream & out = &std::cout, uint8_t settings = (ON_EXIT | NOW))
Definition at line 20 of file timing.cpp.
References NOW, setStart(), and settings.
StopWatch() [3/4]
StopWatch::StopWatch (const char * scope, olstream && out = &std::cout, uint8_t settings = (ON_EXIT | NOW))
Definition at line 25 of file timing.cpp.
References NOW, setStart(), and settings.
StopWatch() [4/4]
StopWatch::StopWatch (const char * scope, olstream * out, uint8_t settings = (ON_EXIT | NOW))
Definition at line 30 of file timing.cpp.
References NOW, setStart(), and settings.
~StopWatch()
StopWatch::~StopWatch ()
Definition at line 35 of file timing.cpp.
References ON_EXIT, ref, and settings.
Member Function Documentation
setStart()
void StopWatch::setStart ()
Definition at line 42 of file timing.cpp.
References ref.
Referenced by StopWatch().
getDuration()
double StopWatch::getDuration ()
Definition at line 45 of file timing.cpp.
References ref.
print() [1/2]
void StopWatch::print ()
Definition at line 49 of file timing.cpp.
References output, ref, and scope.
Referenced by end().
print() [2/2]
void StopWatch::print (olstream && out)
Definition at line 53 of file timing.cpp.
References ref, and scope.
end() [1/2]
void StopWatch::end ()
Definition at line 57 of file timing.cpp.
References print(), and settings.
end() [2/2]
void StopWatch::end (olstream && out)
Definition at line 61 of file timing.cpp.
References print(), and settings.
Member Data Documentation
ref
CHRONO::time_point<CHRONO::high_resolution_clock> StopWatch::ref private
Definition at line 21 of file timing.h.
Referenced by ~StopWatch(), getDuration(), print(), and setStart().
settings
uint8_t StopWatch::settings private
Definition at line 22 of file timing.h.
Referenced by StopWatch(), ~StopWatch(), and end().
buff
olstream StopWatch::buff private
Definition at line 23 of file timing.h.
output
olstream * StopWatch::output private
Definition at line 23 of file timing.h.
Referenced by print().
scope
const char* StopWatch::scope private
Definition at line 24 of file timing.h.
Referenced by print().
ON_EXIT
constexpr uint8_t StopWatch::ON_EXIT = 2 static constexpr
Definition at line 26 of file timing.h.
Referenced by ~StopWatch().
NOW
constexpr uint8_t StopWatch::NOW = 1 static constexpr
Definition at line 27 of file timing.h.
Referenced by StopWatch().
The documentation for this class was generated from the following files:
lib-vs/additions/cpp-tools/src/timing.h
lib-vs/additions/cpp-tools/src/timing.cpp