VisionServer: Request Class Reference
Request Class Reference
#include <http.h>
Public Member Functions
Request ()
Request (Method method, const std::string &resource, const HeaderList &headers, const std::string &body=std::string(), Version version=Version::HTTP_1_1)
Request (const std::string &reqest)
Request (const Request &other)
Request (Request &&other)
~Request ()=default
void parse (const std::string &input)
std::string getSerialized () const
Version * intVersion ()
Method * intMethod ()
std::string * intResource ()
HeaderList * intHeaders ()
std::string * intBody ()
const Version getVersion () const
const Method getMethod () const
const std::string & getResource () const
const HeaderList & getHeaders () const
const std::string & getBody () const
Static Public Member Functions
static std::string getSerialized (Method method, const std::string &resource, std::vector< Segment > &headers, const std::string &body=std::string(), Version version=Version::HTTP_1_1)
static void getSerialized (std::ostream &buffer, Method method, const std::string &resource, std::vector< Segment > &headers, const std::string &body=std::string(), Version version=Version::HTTP_1_1)
Private Attributes
Method method
std::string resource
Version version
HeaderList headers
std::string body
Detailed Description
Definition at line 151 of file http.h.
Constructor & Destructor Documentation
Request() [1/5]
Request::Request () inline
Definition at line 160 of file http.h.
Request() [2/5]
Request::Request (Method method, const std::string & resource, const HeaderList & headers, const std::string & body = std::string(), Version version = Version::HTTP_1_1) inline
Definition at line 161 of file http.h.
Request() [3/5]
Request::Request (const std::string & reqest)
Definition at line 258 of file http.cpp.
References parse().
Request() [4/5]
Request::Request (const Request & other) inline
Definition at line 164 of file http.h.
Request() [5/5]
Request::Request (Request && other) inline
Definition at line 165 of file http.h.
~Request()
Request::~Request () default
Member Function Documentation
parse()
void Request::parse (const std::string & input)
Definition at line 262 of file http.cpp.
References HeaderList::add(), body, clearEnd(), ERROR, Versions::getType(), Methods::getType(), headers, method, HeaderList::reset(), resource, space, and version.
Referenced by Request().
getSerialized() [1/3]
std::string Request::getSerialized () const
Definition at line 284 of file http.cpp.
References HeaderList::allHeaders(), body, endline, Methods::getString(), Versions::getString(), headers, method, resource, space, and version.
intVersion()
Version * Request::intVersion () inline
Definition at line 171 of file http.h.
References version.
intMethod()
Method * Request::intMethod () inline
Definition at line 172 of file http.h.
References method.
intResource()
std::string * Request::intResource () inline
Definition at line 173 of file http.h.
References resource.
intHeaders()
HeaderList * Request::intHeaders () inline
Definition at line 174 of file http.h.
References headers.
intBody()
std::string * Request::intBody () inline
Definition at line 175 of file http.h.
References body.
getVersion()
const Version Request::getVersion () const inline
Definition at line 177 of file http.h.
References version.
getMethod()
const Method Request::getMethod () const inline
Definition at line 178 of file http.h.
References method.
getResource()
const std::string & Request::getResource () const inline
Definition at line 179 of file http.h.
References resource.
getHeaders()
const HeaderList & Request::getHeaders () const inline
Definition at line 180 of file http.h.
References headers.
getBody()
const std::string & Request::getBody () const inline
Definition at line 181 of file http.h.
References body.
getSerialized() [2/3]
std::string Request::getSerialized (Method method, const std::string & resource, std::vector< Segment > & headers, const std::string & body = std::string(), Version version = Version::HTTP_1_1) static
Definition at line 294 of file http.cpp.
References body, endline, Methods::getString(), Versions::getString(), headers, method, resource, space, and version.
getSerialized() [3/3]
void Request::getSerialized (std::ostream & buffer, Method method, const std::string & resource, std::vector< Segment > & headers, const std::string & body = std::string(), Version version = Version::HTTP_1_1) static
Definition at line 305 of file http.cpp.
References body, endline, Methods::getString(), Versions::getString(), headers, method, resource, space, and version.
Member Data Documentation
method
Method Request::method private
Definition at line 153 of file http.h.
Referenced by getMethod(), getSerialized(), intMethod(), and parse().
resource
std::string Request::resource private
Definition at line 154 of file http.h.
Referenced by getResource(), getSerialized(), intResource(), and parse().
version
Version Request::version private
Definition at line 155 of file http.h.
Referenced by getSerialized(), getVersion(), intVersion(), and parse().
headers
HeaderList Request::headers private
Definition at line 156 of file http.h.
Referenced by getHeaders(), getSerialized(), intHeaders(), and parse().
body
std::string Request::body private
Definition at line 157 of file http.h.
Referenced by getBody(), getSerialized(), intBody(), and parse().
The documentation for this class was generated from the following files:
lib-vs/additions/cpp-tools/src/server/http.h
lib-vs/additions/cpp-tools/src/server/http.cpp