VisionServer: HttpServer::HttpHandler Class Reference
HttpServer::HttpHandler Class Reference
#include <server.h>
Public Member Functions
HttpHandler (HttpServer &server)
virtual void respond (const int socket, const char *ip, const int readlen, const std::string &input, HttpFormatter *formatter)
Static Public Member Functions
static const char * safeMime (const char *path)
Protected Member Functions
HttpHandler ()=delete
HttpHandler (HttpServer *outer)
~HttpHandler ()=default
virtual std::string resourceMapper (std::string &&root, const std::string &requested)
Protected Attributes
HttpServer * that
Response response
Request request_buff
Friends
class HttpServer
Detailed Description
Definition at line 70 of file server.h.
Constructor & Destructor Documentation
HttpHandler() [1/3]
HttpServer::HttpHandler::HttpHandler () protected delete
HttpHandler() [2/3]
HttpServer::HttpHandler::HttpHandler (HttpServer * outer) inline protected
Definition at line 79 of file server.h.
~HttpHandler()
HttpServer::HttpHandler::~HttpHandler () protected default
HttpHandler() [3/3]
HttpServer::HttpHandler::HttpHandler (HttpServer & server) inline
Definition at line 86 of file server.h.
Member Function Documentation
resourceMapper()
std::string HttpServer::HttpHandler::resourceMapper (std::string && root, const std::string & requested) protected virtual
Definition at line 72 of file server.cpp.
References HttpServer::root.
safeMime()
const char * HttpServer::HttpHandler::safeMime (const char * path) static
Definition at line 87 of file server.cpp.
References getMegaMimeType().
respond()
void HttpServer::HttpHandler::respond (const int socket, const char * ip, const int readlen, const std::string & input, HttpFormatter * formatter) virtual
Definition at line 95 of file server.cpp.
References HeaderList::add(), BAD_REQUEST, CONNECT, DELETE, ERROR, GET, Codes::getString(), HEAD, HTTP_1_0, BaseServer::ip, METHOD_NOT_ALLOWED, NOT_FOUND, NOT_IMPLEMENTED, OK, HttpServer::HttpFormatter::onRequest(), HttpServer::HttpFormatter::onResponse(), OPTIONS, PATCH, POST, PUT, replace(), and TRACE.
Friends And Related Function Documentation
HttpServer
friend class HttpServer friend
Definition at line 71 of file server.h.
Member Data Documentation
that
HttpServer* HttpServer::HttpHandler::that protected
Definition at line 74 of file server.h.
response
Response HttpServer::HttpHandler::response protected
Definition at line 75 of file server.h.
request_buff
Request HttpServer::HttpHandler::request_buff protected
Definition at line 76 of file server.h.
The documentation for this class was generated from the following files:
lib-vs/additions/cpp-tools/src/server/server.h
lib-vs/additions/cpp-tools/src/server/server.cpp