VisionServer: HttpServer Class Reference
HttpServer Class Reference
#include <server.h>
Classes
class HttpFormatter
class HttpHandler
Public Member Functions
HttpServer ()=delete
HttpServer (const olstream &logger, const char *root=progdir.getDir(), std::atomic< bool > *control=nullptr, Version version=Version::HTTP_1_1, const char *port="http", int max_clients=5)
HttpServer (olstream &&logger=&std::cout, const char *root=progdir.getDir(), std::atomic< bool > *control=nullptr, Version version=Version::HTTP_1_1, const char *port="http", int max_clients=5)
~HttpServer ()=default
const char * getRoot () const
Version getVersion () const
void setLog (const std::ios::openmode modes)
void setLog (const char *file)
void setLog (const char *file, const std::ios::openmode modes)
void setLog (std::ostream *stream)
void setLog (const olstream &target)
void setLog (olstream &&target)
void stop ()
void estop ()
template<class handler_t = HttpHandler, class formatter_t = HttpFormatter>
void serve ()
template<class handler_t = HttpHandler, class formatter_t = HttpFormatter>
void serve1_0 ()
template<class handler_t = HttpHandler, class formatter_t = HttpFormatter>
void serve1_1 ()
template<class handler_t = HttpHandler, class formatter_t = HttpFormatter>
void serveThread ()
template<class handler_t = HttpHandler, class formatter_t = HttpFormatter>
void serveThread1_0 ()
template<class handler_t = HttpHandler, class formatter_t = HttpFormatter>
void serveThread1_1 ()
Public Member Functions inherited from BaseServer
BaseServer (const char *ip, const char *port, int connections=5, bool reusable=true, int family=AF_INET, int socktype=SOCK_STREAM, int flags=AI_PASSIVE)
~BaseServer ()
void getServerAddr ()
void getSock ()
void bindSock ()
void startListen ()
Protected Member Functions
void prepServer ()
bool defLog ()
void lerror (const char *message)
void ex_lerror (const char *message)
Static Protected Member Functions
template<class handler_t = HttpHandler, class formatter_t = HttpFormatter>
static void serveWorker1_0 (HttpServer *inst)
template<class handler_t = HttpHandler, class formatter_t = HttpFormatter>
static void serveWorker1_1 (HttpServer *inst)
Protected Attributes
std::atomic< bool > l_online
const char * root
Version version
std::atomic< bool > * online
olstream logs
Protected Attributes inherited from BaseServer
addrinfo * list
SOCK_T sockmain
Additional Inherited Members
Static Public Member Functions inherited from BaseServer
static void getAddrs (const char *ip, const char *port, addrinfo *hints, addrinfo **list)
static void getAddrs (addrinfo **list, const char *ip, const char *port, int family=AF_UNSPEC, int socktype=SOCK_STREAM, int flags=AI_PASSIVE)
static void getAddr4 (addrinfo **list, const char *ip, const char *port, int socktype=SOCK_STREAM, int flags=AI_PASSIVE)
static void getAddr6 (addrinfo **list, const char *ip, const char *port, int socktype=SOCK_STREAM, int flags=AI_PASSIVE)
static void getServerAddr (addrinfo **list, const char *port, int family=AF_INET, int socktype=SOCK_STREAM)
static void getServerAddr (addrinfo **list)
static void addrListVec (addrinfo *list, std::vector< addrinfo > &vec)
static SOCK_T getSock (addrinfo *addr, bool reuse=true)
static SOCK_T getSock (const addrinfo &addr, bool reuse=true)
static SOCK_T bindNewSock (addrinfo *addr, bool reuse=true)
static void bindSock (SOCK_T sock, addrinfo *addr)
static void startListen (SOCK_T sock, int connections)
Detailed Description
Definition at line 24 of file server.h.
Constructor & Destructor Documentation
HttpServer() [1/3]
HttpServer::HttpServer () delete
HttpServer() [2/3]
HttpServer::HttpServer (const olstream & logger, const char * root = progdir.getDir(), std::atomic< bool > * control = nullptr, Version version = Version::HTTP_1_1, const char * port = "http", int max_clients = 5)
Definition at line 268 of file server.cpp.
References BaseServer::getServerAddr(), l_online, logs, online, and olstream::setModes().
HttpServer() [3/3]
HttpServer::HttpServer (olstream && logger = &std::cout, const char * root = progdir.getDir(), std::atomic< bool > * control = nullptr, Version version = Version::HTTP_1_1, const char * port = "http", int max_clients = 5)
Definition at line 287 of file server.cpp.
References BaseServer::getServerAddr(), l_online, logs, online, and olstream::setModes().
~HttpServer()
HttpServer::~HttpServer () default
Member Function Documentation
prepServer()
void HttpServer::prepServer () protected
Definition at line 12 of file server.cpp.
References BaseServer::bindSock(), BaseServer::getSock(), and BaseServer::startListen().
Referenced by serveWorker1_0(), and serveWorker1_1().
defLog()
bool HttpServer::defLog () inline protected
Definition at line 17 of file server.cpp.
References olstream::getStream(), and logs.
Referenced by ex_lerror(), and lerror().
lerror()
void HttpServer::lerror (const char * message) protected
Definition at line 20 of file server.cpp.
References dateStamp(), defLog(), logs, and newline.
Referenced by serveWorker1_0(), and serveWorker1_1().
ex_lerror()
void HttpServer::ex_lerror (const char * message) protected
Definition at line 28 of file server.cpp.
References dateStamp(), defLog(), logs, and newline.
serveWorker1_0()
template<class handler_t , class formatter_t > void HttpServer::serveWorker1_0 (HttpServer * inst) static protected
Definition at line 7 of file server.inc.
References getSockIp(), HTTP_1_0, l_online, lerror(), online, prepServer(), BaseServer::sockmain, and version.
serveWorker1_1()
template<class handler_t , class formatter_t > void HttpServer::serveWorker1_1 (HttpServer * inst) static protected
Definition at line 59 of file server.inc.
References getSockIp(), HTTP_1_1, l_online, lerror(), online, prepServer(), BaseServer::sockmain, and version.
getRoot()
const char * HttpServer::getRoot () const inline
Definition at line 114 of file server.h.
References root.
getVersion()
Version HttpServer::getVersion () const inline
Definition at line 115 of file server.h.
References version.
setLog() [1/6]
void HttpServer::setLog (const std::ios::openmode modes)
Definition at line 307 of file server.cpp.
References logs, and olstream::setModes().
setLog() [2/6]
void HttpServer::setLog (const char * file)
Definition at line 310 of file server.cpp.
References logs, and olstream::setStream().
setLog() [3/6]
void HttpServer::setLog (const char * file, const std::ios::openmode modes)
Definition at line 313 of file server.cpp.
References logs, and olstream::setStream().
setLog() [4/6]
void HttpServer::setLog (std::ostream * stream)
Definition at line 316 of file server.cpp.
References logs, and olstream::setStream().
setLog() [5/6]
void HttpServer::setLog (const olstream & target)
Definition at line 319 of file server.cpp.
References logs.
setLog() [6/6]
void HttpServer::setLog (olstream && target)
Definition at line 322 of file server.cpp.
References logs.
stop()
void HttpServer::stop ()
Definition at line 326 of file server.cpp.
References l_online, and online.
estop()
void HttpServer::estop ()
Definition at line 330 of file server.cpp.
References logs, BaseServer::sockmain, and withTime().
serve()
template<class handler_t , class formatter_t > void HttpServer::serve
Definition at line 137 of file server.inc.
References HTTP_1_0, HTTP_1_1, HTTP_2_0, logs, and version.
serve1_0()
template<class handler_t , class formatter_t > void HttpServer::serve1_0
Definition at line 154 of file server.inc.
serve1_1()
template<class handler_t , class formatter_t > void HttpServer::serve1_1
Definition at line 158 of file server.inc.
serveThread()
template<class handler_t , class formatter_t > void HttpServer::serveThread
Definition at line 163 of file server.inc.
References HTTP_1_0, HTTP_1_1, HTTP_2_0, logs, and version.
serveThread1_0()
template<class handler_t , class formatter_t > void HttpServer::serveThread1_0
Definition at line 180 of file server.inc.
serveThread1_1()
template<class handler_t , class formatter_t > void HttpServer::serveThread1_1
Definition at line 184 of file server.inc.
Member Data Documentation
l_online
std::atomic<bool> HttpServer::l_online protected
Definition at line 30 of file server.h.
Referenced by HttpServer(), serveWorker1_0(), serveWorker1_1(), and stop().
root
const char* HttpServer::root protected
Definition at line 31 of file server.h.
Referenced by getRoot(), and HttpServer::HttpHandler::resourceMapper().
version
Version HttpServer::version protected
Definition at line 32 of file server.h.
Referenced by getVersion(), serve(), serveThread(), serveWorker1_0(), and serveWorker1_1().
online
std::atomic<bool>* HttpServer::online protected
Definition at line 33 of file server.h.
Referenced by HttpServer(), serveWorker1_0(), serveWorker1_1(), and stop().
logs
olstream HttpServer::logs protected
Definition at line 34 of file server.h.
Referenced by HttpServer(), defLog(), estop(), ex_lerror(), HttpServer::HttpFormatter::getStream(), lerror(), serve(), serveThread(), and setLog().
The documentation for this class was generated from the following files:
lib-vs/additions/cpp-tools/src/server/server.h
lib-vs/additions/cpp-tools/src/server/server.cpp
lib-vs/additions/cpp-tools/src/server/server.inc