VisionServer: lib-vs/additions/cpp-tools/src/server/mimetype.h File Reference
mimetype.h File Reference
#include <string.h>
#include <stdio.h>
#include <ctype.h>
#include <stdlib.h>
#include <wchar.h>
#include <assert.h>
#include <wctype.h>
#include <limits.h>
#include <stdbool.h>
Classes
struct MegaFileInfo
Macros
#define _MEGAMIMES_H_
#define FILE_PATH_SEP '\\'
#define THREAD_LOCAL thread_local
#define MAX_LINE_SIZE 256
Enumerations
enum {
EXTENSION_POS , MIMENAME_POS , MIMETYPE_POS , MAGICNUMBER_POS ,
COMPONENTS_NUMBER
}
Functions
const char * getMegaMimeType (const char *pFileName)
Get The Mime Type Of A File Or A File Extension.
const char ** getMegaMimeExtensions (const char *pMimeType)
Get The Extensions associated with Mime Types.
MegaFileInfo * getMegaFileInformation (const char *pFilePath)
Get information about a file.
bool isTextFile (const char *path)
Determines if a file is a text file.
bool isBinaryFile (const char *path)
Determines if ia file is a binary file.
const char * getMegaTextFileEncoding (const char *path)
Gets the encoding for a text file.
void freeMegaFileInfo (MegaFileInfo *pData)
Frees a MegaFileInfo structure.
void freeMegaString (char *pData)
Frees a string.
void freeMegaStringArray (char **pData)
Frees an array of strings.
Variables
const char * MegaMimeTypes [][COMPONENTS_NUMBER]
Class Documentation
MegaFileInfo
struct MegaFileInfo
Definition at line 50 of file mimetype.h.
Class Members
char * mBaseDir
char * mBaseName
char * mExtension
long long mFileSize
const char * mMimeType
const char * mMimeName
bool mTextFile
const char * mTextEncoding
Macro Definition Documentation
_MEGAMIMES_H_
#define _MEGAMIMES_H_
Definition at line 18 of file mimetype.h.
FILE_PATH_SEP
#define FILE_PATH_SEP '\\'
Definition at line 31 of file mimetype.h.
THREAD_LOCAL
#define THREAD_LOCAL thread_local
Definition at line 37 of file mimetype.h.
MAX_LINE_SIZE
#define MAX_LINE_SIZE 256
Definition at line 40 of file mimetype.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
EXTENSION_POS
MIMENAME_POS
MIMETYPE_POS
MAGICNUMBER_POS
COMPONENTS_NUMBER
Definition at line 20 of file mimetype.h.
Function Documentation
getMegaMimeType()
const char * getMegaMimeType (const char * pFileName)
Get The Mime Type Of A File Or A File Extension.
The function gets the mime type of the file specified by the path. The function does not check if the file exists or not. It just uses the file's basename including the extension to lookup the mime type. The filename can also be an extension only, which is preceeded by a ".". Example (.mp3, mega.mp3, /usr/lib/mega.mp3) will all return the same thing.
Parameters
pFileName The name of the file whose mime type should be determined
Returns
the mimetype of the file or NULL if no mimetype is known for the file. The string returned should be freed
Definition at line 191 of file mimetype.c.
References FILE_PATH_SEP, and searchThroughMimes().
Referenced by HttpServer::HttpHandler::safeMime().
getMegaMimeExtensions()
const char ** getMegaMimeExtensions (const char * pMimeType)
Get The Extensions associated with Mime Types.
The function gets the file extensions for the mimetype. The mimetype should be in the form type/sub-type, otherwise it is invalid. An optional version can be added to the string. Any other trailing details are ignored. * character can be used to match everything. Eg video/ returns all video file extensions and * returns all file extensions
Parameters
pMimeType The mimetype whose extension is to be determined
Returns
An array of extension names. The array is terminated by a NULL. The function returns NULL if no extensions were found for the mime types given.
Definition at line 213 of file mimetype.c.
References searchThroughMimes().
getMegaFileInformation()
MegaFileInfo * getMegaFileInformation (const char * pFilePath)
Get information about a file.
Gets information about the file, such as the encoding, the mime name the mime type and the the file size.
Parameters
pFilePath The name of the file whose information is to be determined.
Returns
the information about the file. The structure returned should be freed with freeMegaFileInfo. The function returns NULL if the file does not exists, or the user does not have permissions to read from the file
Definition at line 280 of file mimetype.c.
References getMegaTextFileEncoding(), isNotReadableFile(), isTextFile(), MegaFileInfo::mBaseDir, MegaFileInfo::mBaseName, MegaFileInfo::mExtension, MegaFileInfo::mFileSize, MegaFileInfo::mMimeName, MegaFileInfo::mMimeType, MegaFileInfo::mTextEncoding, MegaFileInfo::mTextFile, searchThroughMimes(), and splitFileParts().
isTextFile()
bool isTextFile (const char * path)
Determines if a file is a text file.
Returns whether the file is a text file or not. The function is a really slow function, as it scans through every byte, checking to see if it is a control character or not. The encoding is taken into consideration.
Parameters
path The path name for the file. If the file des not exist, false is returned.
Returns
whether the file is a text file or not. Returns false if the file does not eixist.
Definition at line 236 of file mimetype.c.
References guessFileEncoding(), and isNotReadableFile().
Referenced by getMegaFileInformation(), and isBinaryFile().
isBinaryFile()
bool isBinaryFile (const char * path)
Determines if ia file is a binary file.
Returns whether the file is a binary file or not
Parameters
path The path name for the file.
Returns
whether the file is a binary file or not. Reutrns false if the file does not exist.
Definition at line 273 of file mimetype.c.
References isTextFile().
getMegaTextFileEncoding()
const char * getMegaTextFileEncoding (const char * path)
Gets the encoding for a text file.
Precondition
The file is assumed to be a text file. Use isTextFile() to check the file before calling this function.
The function gets the encoding of the file. The string can be UTF-8, UTF-8, UTF-16LE, UTF-16 UTF-32, UTF-32BE, UTF-32LE. The function does not check if the file is binary file or a text file. It is assumend that you are really sure that it is a binary file. You can use isTextFile() to first check if it is a text file, before using the function.
Parameters
path The path name for the file
Returns
the file encoding or empty string if the file does not exist or cannot be read.
Definition at line 314 of file mimetype.c.
References guessFileEncoding().
Referenced by getMegaFileInformation().
freeMegaFileInfo()
void freeMegaFileInfo (MegaFileInfo * pData)
Frees a MegaFileInfo structure.
The function deallocates and destroys a MegaFileInfo structure. If the structure is NULL, the function simply and does nothing.
Parameters
pData The MegaFileInfo structure to be freed
Definition at line 319 of file mimetype.c.
References MegaFileInfo::mBaseDir, MegaFileInfo::mBaseName, and MegaFileInfo::mExtension.
freeMegaString()
void freeMegaString (char * pData)
Frees a string.
The function deallocates and frees a string returned by any of the functions. The difference between this function and the std library free , is that this function does nothing if its argument is NULL
Parameters
pData The string to be freed
Definition at line 330 of file mimetype.c.
freeMegaStringArray()
void freeMegaStringArray (char ** pData)
Frees an array of strings.
The function frees the dynamically allocated array of dynamically allocated strings returned by getMegaMimeExtensions. The function simply does nothing if its argument is NULL
Parameters
pData The string array to be freed.
Definition at line 335 of file mimetype.c.
Variable Documentation
MegaMimeTypes
const char* MegaMimeTypes[][COMPONENTS_NUMBER] extern
MegaFileInfo is the structure that conains information about a file. The structure is returned by getMegaFileInfo. It contains all the details that is needed about a file.
Definition at line 341 of file mimetype.c.
Referenced by searchThroughMimes().