VisionServer: sys::cpu Namespace Reference
sys::cpu Namespace Reference
Functions
size_t getIdle (const LineParse &data)
size_t getActive (const LineParse &data)
void readMain (LineParse &container)
void readVector (std::vector< LineParse > &container)
void convertData (LineParse &snapshot1, LineParse &snapshot2, ActivityData &output)
void convertVectorData (std::vector< LineParse > &snapshot1, std::vector< LineParse > &snapshot2, std::vector< ActivityData > &output)
Function Documentation
getIdle()
size_t sys::cpu::getIdle (const LineParse & data)
Definition at line 303 of file stats.cpp.
Referenced by convertData(), convertVectorData(), and sys::cpuPercent().
getActive()
size_t sys::cpu::getActive (const LineParse & data)
Definition at line 307 of file stats.cpp.
Referenced by convertData(), convertVectorData(), and sys::cpuPercent().
readMain()
void sys::cpu::readMain (LineParse & container)
Definition at line 311 of file stats.cpp.
Referenced by sys::cpuPercent().
readVector()
void sys::cpu::readVector (std::vector< LineParse > & container)
Definition at line 320 of file stats.cpp.
convertData()
void sys::cpu::convertData (LineParse & snapshot1, LineParse & snapshot2, ActivityData & output)
Definition at line 337 of file stats.cpp.
References getActive(), and getIdle().
convertVectorData()
void sys::cpu::convertVectorData (std::vector< LineParse > & snapshot1, std::vector< LineParse > & snapshot2, std::vector< ActivityData > & output)
Definition at line 345 of file stats.cpp.
References getActive(), and getIdle().