VisionServer: sys Namespace Reference
sys Namespace Reference
Namespaces
namespace cpu
Functions
float cpuTemp ()
float gpuTemp ()
float cpuPercent (CHRONO::duration< CHRONO::seconds::rep, CHRONO::seconds::period > interval)
Function Documentation
cpuTemp()
float sys::cpuTemp ()
Definition at line 359 of file stats.cpp.
gpuTemp()
float sys::gpuTemp ()
Definition at line 370 of file stats.cpp.
cpuPercent()
float sys::cpuPercent (CHRONO::duration< CHRONO::seconds::rep, CHRONO::seconds::period > interval)
Definition at line 381 of file stats.cpp.
References sys::cpu::getActive(), sys::cpu::getIdle(), and sys::cpu::readMain().