VisionServer: Versions Struct Reference
Versions Struct Reference
#include <http.h>
Static Public Member Functions
static Version getType (const std::string &str)
static std::string getString (Version version)
Static Private Attributes
static const std::unordered_map< std::string, Version > typemap
static const std::unordered_map< Version, std::string > stringmap
Detailed Description
Definition at line 45 of file http.h.
Member Function Documentation
getType()
Version Versions::getType (const std::string & str) static
Definition at line 14 of file http.cpp.
References ERROR, and typemap.
Referenced by Response::Response(), and Request::parse().
getString()
std::string Versions::getString (Version version) static
Definition at line 21 of file http.cpp.
References stringmap.
Referenced by Request::getSerialized(), Response::getSerialized(), and HttpServer::HttpFormatter::onServerStart().
Member Data Documentation
typemap
const std::unordered_map< std::string, Version > Versions::typemap static private
Initial value:
= {
    {"HTTP/1.0", Version::HTTP_1_0},
    {"HTTP/1.1", Version::HTTP_1_1},
    {"HTTP/2.0", Version::HTTP_2_0},
}
Definition at line 47 of file http.h.
Referenced by getType().
stringmap
const std::unordered_map< Version, std::string > Versions::stringmap static private
Initial value:
= {
    {Version::HTTP_1_0, "HTTP/1.0"},
    {Version::HTTP_1_1, "HTTP/1.1"},
    {Version::HTTP_2_0, "HTTP/2.0"},
}
Definition at line 48 of file http.h.
Referenced by getString().
The documentation for this struct was generated from the following files:
lib-vs/additions/cpp-tools/src/server/http.h
lib-vs/additions/cpp-tools/src/server/http.cpp