VisionServer: vs2::VisionServer::OutputStream Struct Reference
vs2::VisionServer::OutputStream Struct Reference
Public Member Functions
OutputStream (cs::MjpegServer &&s)
OutputStream (std::string_view n)
OutputStream (std::string_view n, int p)
OutputStream (const OutputStream &o)
OutputStream (OutputStream &&o)
~OutputStream ()
void setSourceIdx (int i)
void setPipelineIdx (uint16_t i)
void setCameraIdx (uint16_t i)
Static Public Member Functions
static const std::shared_ptr< nt::NetworkTable > & ntable ()
Protected Member Functions
void syncIdx ()
Private Attributes
const std::shared_ptr< nt::NetworkTable > table
std::atomic_int local_idx {0}
Friends
class VisionServer
Detailed Description
Definition at line 153 of file visionserver2.h.
Constructor & Destructor Documentation
OutputStream() [1/5]
VisionServer::OutputStream::OutputStream (cs::MjpegServer && s)
Definition at line 221 of file visionserver2.cpp.
References local_idx, and table.
OutputStream() [2/5]
vs2::VisionServer::OutputStream::OutputStream (std::string_view n) inline
Definition at line 162 of file visionserver2.h.
OutputStream() [3/5]
vs2::VisionServer::OutputStream::OutputStream (std::string_view n, int p) inline
Definition at line 164 of file visionserver2.h.
OutputStream() [4/5]
vs2::VisionServer::OutputStream::OutputStream (const OutputStream & o) inline
Definition at line 166 of file visionserver2.h.
OutputStream() [5/5]
vs2::VisionServer::OutputStream::OutputStream (OutputStream && o) inline
Definition at line 168 of file visionserver2.h.
~OutputStream()
VisionServer::OutputStream::~OutputStream ()
Definition at line 227 of file visionserver2.cpp.
Member Function Documentation
ntable()
static const std::shared_ptr< nt::NetworkTable > & vs2::VisionServer::OutputStream::ntable () inline static
Definition at line 156 of file visionserver2.h.
References vs2::VisionServer::ntable(), and vs2::VisionServer::streams.
Referenced by vs2::VisionServer::Init().
setSourceIdx()
void VisionServer::OutputStream::setSourceIdx (int i)
Definition at line 228 of file visionserver2.cpp.
References vs2::VisionServer::cameras, vs2::VisionServer::inst(), vs2::VisionServer::numCameras(), vs2::VisionServer::numPipelines(), and vs2::VisionServer::pipelines.
Referenced by setCameraIdx(), and setPipelineIdx().
setPipelineIdx()
void vs2::VisionServer::OutputStream::setPipelineIdx (uint16_t i) inline
Definition at line 173 of file visionserver2.h.
References setSourceIdx().
setCameraIdx()
void vs2::VisionServer::OutputStream::setCameraIdx (uint16_t i) inline
Definition at line 174 of file visionserver2.h.
References setSourceIdx().
syncIdx()
void VisionServer::OutputStream::syncIdx () protected
Definition at line 238 of file visionserver2.cpp.
References vs2::VisionServer::cameras, vs2::VisionServer::inst(), vs2::VisionServer::numCameras(), vs2::VisionServer::numPipelines(), and vs2::VisionServer::pipelines.
Friends And Related Function Documentation
VisionServer
friend class VisionServer friend
Definition at line 154 of file visionserver2.h.
Member Data Documentation
table
const std::shared_ptr<nt::NetworkTable> vs2::VisionServer::OutputStream::table private
Definition at line 180 of file visionserver2.h.
Referenced by OutputStream().
local_idx
std::atomic_int vs2::VisionServer::OutputStream::local_idx {0} private
Definition at line 181 of file visionserver2.h.
Referenced by OutputStream().
The documentation for this struct was generated from the following files:
lib-vs/src/core/visionserver2.h
lib-vs/src/core/visionserver2.cpp