VisionServer: Codes Struct Reference
Codes Struct Reference
#include <http.h>
Static Public Member Functions
static Code getType (const std::string &str)
static Code getType (int code)
static std::string getString (Code code)
static std::string getString (int code)
Static Private Attributes
static const std::unordered_map< std::string, Code > typemap
static const std::unordered_map< Code, std::string > stringmap
Detailed Description
Definition at line 67 of file http.h.
Member Function Documentation
getType() [1/2]
Code Codes::getType (const std::string & str) static
Definition at line 120 of file http.cpp.
References ERROR, and typemap.
Referenced by Response::Response().
getType() [2/2]
Code Codes::getType (int code) static
Definition at line 135 of file http.cpp.
getString() [1/2]
std::string Codes::getString (Code code) static
Definition at line 138 of file http.cpp.
References stringmap.
Referenced by Response::getSerialized(), and HttpServer::HttpHandler::respond().
getString() [2/2]
std::string Codes::getString (int code) static
Definition at line 145 of file http.cpp.
References stringmap.
Member Data Documentation
typemap
const std::unordered_map< std::string, Code > Codes::typemap static private
Initial value:
= {
    {"100 Continue", Code::CONTINUE}, {"200 OK", Code::OK},
    {"201 Created", Code::CREATED}, {"202 Accepted", Code::ACCEPTED},
    {"204 No Content", Code::NO_CONTENT}, {"205 Reset Content", Code::RESET_CONTENT},
    {"206 Partial Content", Code::PARTIAL_CONTENT},
    {"300 Multiple Choices", Code::MULTIPLE_CHOICES},
    {"301 Moved Permanently", Code::MOVED_PERMANENTLY},
    {"302 Found", Code::FOUND}, {"400 Bad Request", Code::BAD_REQUEST},
    {"401 Unauthorized", Code::UNAUTHORIZED},
    {"402 Payment Required", Code::PAYMENT_REQUIRED},
    {"403 Forbidden", Code::FORBIDDEN},  {"404 Not Found", Code::NOT_FOUND},
    {"405 Method Not Allowed", Code::METHOD_NOT_ALLOWED},
    {"406 Not Acceptable", Code::NOT_ACCEPTABLE},
    {"408 Request Timeout", Code::REQUEST_TIMEOUT}, {"409 Conflict", Code::CONFLICT},
    {"410 Gone", Code::GONE}, {"411 Length Required", Code::LENGTH_REQUIRED},
    {"414 URI Too Long", Code::URI_TOO_LONG},
    {"415 Unsupported Media Type", Code::UNSUPPORTED_MEDIA_TYPE},
    {"418 I'm a teapot", Code::IM_A_TEAPOT},
    {"500 Internal Server Error", Code::INTERNAL_SERVER_ERROR},
    {"501 Not Implemented", Code::NOT_IMPLEMENTED}, {"502 Bad Gateway", Code::BAD_GATEWAY},
    {"503 Service Unavailable", Code::SERVICE_UNAVAILABLE},
    {"504 Gateway Timeout", Code::GATEWAY_TIMEOUT},
    {"505 HTTP Version Not Supported", Code::HTTP_VERSION_NOT_SUPPORTED},
    {"510 Not Extended", Code::NOT_EXTENDED},
    {"511 Network Authentication Required", Code::NETWORK_AUTHICATION_REQIRED},
}
Definition at line 69 of file http.h.
Referenced by getType().
stringmap
const std::unordered_map< Code, std::string > Codes::stringmap static private
Initial value:
= {
    {Code::CONTINUE, "100 Continue"}, {Code::OK, "200 OK"},
    {Code::CREATED, "201 Created"}, {Code::ACCEPTED, "202 Accepted"},
    {Code::NO_CONTENT, "204 No Content"}, {Code::RESET_CONTENT, "205 Reset Content"},
    {Code::PARTIAL_CONTENT, "206 Partial Content"},
    {Code::MULTIPLE_CHOICES, "300 Multiple Choices"},
    {Code::MOVED_PERMANENTLY, "301 Moved Permanently"},
    {Code::FOUND, "302 Found"}, {Code::BAD_REQUEST, "400 Bad Request"},
    {Code::UNAUTHORIZED, "401 Unauthorized"},
    {Code::PAYMENT_REQUIRED, "402 Payment Required"},
    {Code::FORBIDDEN, "403 Forbidden"}, {Code::NOT_FOUND, "404 Not Found"},
    {Code::METHOD_NOT_ALLOWED, "405 Method Not Allowed"},
    {Code::NOT_ACCEPTABLE, "406 Not Acceptable"},
    {Code::REQUEST_TIMEOUT, "408 Request Timeout"}, {Code::CONFLICT, "409 Conflict"},
    {Code::GONE, "410 Gone"}, {Code::LENGTH_REQUIRED, "411 Length Required"},
    {Code::URI_TOO_LONG, "414 URI Too Long"},
    {Code::UNSUPPORTED_MEDIA_TYPE, "415 Unsupported Media Type"},
    {Code::IM_A_TEAPOT, "418 I'm a teapot"},
    {Code::INTERNAL_SERVER_ERROR, "500 Internal Server Error"},
    {Code::NOT_IMPLEMENTED, "501 Not Implemented"}, {Code::BAD_GATEWAY, "502 Bad Gateway"},
    {Code::SERVICE_UNAVAILABLE, "503 Service Unavailable"},
    {Code::GATEWAY_TIMEOUT, "504 Gateway Timeout"},
    {Code::HTTP_VERSION_NOT_SUPPORTED, "505 HTTP Version Not Supported"},
    {Code::NOT_EXTENDED, "510 Not Extended"},
    {Code::NETWORK_AUTHICATION_REQIRED, "511 Network Authentication Required"},
}
Definition at line 70 of file http.h.
Referenced by getString().
The documentation for this struct was generated from the following files:
lib-vs/additions/cpp-tools/src/server/http.h
lib-vs/additions/cpp-tools/src/server/http.cpp