VisionServer: lib-vs/additions/cpp-tools/src/threading.h File Reference
threading.h File Reference
#include <thread>
#include <chrono>
#include <atomic>
#include "resources.h"
#include "timing.h"
Functions
template<typename return_t , typename... args_t>
void routineThread (const std::atomic_bool &control, const DayTime tme, const time_t uintv, return_t(*func)(args_t...), args_t... args)
template<typename return_t , typename... args_t>
void p_routineThread (std::atomic_bool **control, const DayTime tme, const time_t uintv, return_t(*func)(args_t...), args_t... args)
template<typename d_rep , typename d_period , typename return_t , typename... args_t>
void loopingThread (std::atomic_bool const &control, CHRONO::duration< d_rep, d_period > interval, CHRONO::duration< d_rep, d_period > uinterval, return_t(*func)(args_t...), args_t... args)
Function Documentation
routineThread()
template<typename return_t , typename... args_t> void routineThread (const std::atomic_bool & control, const DayTime tme, const time_t uintv, return_t(*)(args_t...) func, args_t... args)
Definition at line 13 of file threading.h.
References nextDayTime(), and untilDayTime().
p_routineThread()
template<typename return_t , typename... args_t> void p_routineThread (std::atomic_bool ** control, const DayTime tme, const time_t uintv, return_t(*)(args_t...) func, args_t... args)
Definition at line 32 of file threading.h.
References nextDayTime(), and untilDayTime().
loopingThread()
template<typename d_rep , typename d_period , typename return_t , typename... args_t> void loopingThread (std::atomic_bool const & control, CHRONO::duration< d_rep, d_period > interval, CHRONO::duration< d_rep, d_period > uinterval, return_t(*)(args_t...) func, args_t... args)
Definition at line 52 of file threading.h.