VisionServer: lib-vs/additions/cpp-tools/src/timing.h File Reference
timing.h File Reference
#include <iostream>
#include <chrono>
#include <ctime>
#include "resources.h"
#include "output.h"
Classes
class StopWatch
class ScopeTimer
struct DayTime
Typedefs
typedef unsigned int time_d
Functions
time_d createTOD (int16_t hr, int16_t min, int16_t sec)
time_t untilDayTime (const DayTime &tme)
CHRONO::time_point< CHRONO::system_clock > nextDayTime (const DayTime &tme)
Typedef Documentation
time_d
typedef unsigned int time_d
Definition at line 49 of file timing.h.
Function Documentation
createTOD()
time_d createTOD (int16_t hr, int16_t min, int16_t sec)
Definition at line 66 of file timing.cpp.
untilDayTime()
time_t untilDayTime (const DayTime & tme)
Definition at line 90 of file timing.cpp.
References DayTime::hr, DayTime::min, and DayTime::sec.
Referenced by p_routineThread(), and routineThread().
nextDayTime()
CHRONO::time_point< CHRONO::system_clock > nextDayTime (const DayTime & tme)
Definition at line 104 of file timing.cpp.
References DayTime::hr, DayTime::min, and DayTime::sec.
Referenced by p_routineThread(), and routineThread().